"""Recreate tables with proper enum handling

Revision ID: 76cf542d8310
Revises: f74561835a79
Create Date: 2025-02-26 22:09:53.430002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cf542d8310'
down_revision: Union[str, None] = 'f74561835a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('received', 'sent', 'delivered', 'read', 'failed', name='message_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', name='job_frequency'), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('preferred_time', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'deactivated', name='job_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_id'), 'scheduled_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_jobs_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
