"""improve messages table with agent and user messages

Revision ID: c75b6b8b551a
Revises: 76cf542d8310
Create Date: 2025-03-02 18:11:33.558525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75b6b8b551a'
down_revision: Union[str, None] = '76cf542d8310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_message', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('agent_message', sa.String(), nullable=True))
    op.drop_index('ix_messages_direction', table_name='messages')
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_messages_direction', 'messages', ['direction'], unique=False)
    op.drop_column('messages', 'agent_message')
    op.drop_column('messages', 'user_message')
    # ### end Alembic commands ###
